logger:

web_server:

captive_portal:

mdns:

api:

debug:
  update_interval: 30s

ota:
  password: $name

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: ${name}
    password: !secret wifi_password

  manual_ip:
    static_ip: ${static_ip}
    gateway: !secret gateway
    subnet: !secret subnet

button:
  - platform: restart
    name: Restart

text_sensor:
  - platform: debug
      reset_reason:
        name: Reset Reason
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Wifi SSID
    mac_address:
      name: MAC
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true

sensor:
  - platform: uptime
    name: Uptime

  - platform: wifi_signal
    name: Wifi Signal
    update_interval: 60s