esphome:
  name: $name
  friendly_name: $friendly_name

bk72xx:
  board: generic-bk7231n-qfn32-tuya

debug:
  update_interval: 30s

text_sensor:
  - platform: debug
    reset_reason:
      name: Reset Reason
  
sensor:
  - platform: uptime
    name: Uptime
  - platform: adc
    pin: ADC3
    name: "Battery Level"

binary_sensor:
  - platform: gpio
    pin:
      number: P8
      mode: INPUT
      inverted: False
    name: "Door"
    device_class: door
  - platform: gpio
    pin:
      number: VCC
      mode: INPUT
    name: "Test"
    device_class: battery
    unit_of_measurement: '%'
    update_interval: 5s
    lambda: |-
      return ((id(VCC).state /3.30) * 100.00);

