esphome:
  name: $name
  friendly_name: $friendly_name

esp32:
  board: esp32dev
  variant: esp32c3
  
debug:
  update_interval: 30s

text_sensor:
  - platform: debug
    reset_reason:
      name: Reset Reason
  
sensor:
  - platform: uptime
    name: Uptime

  - platform: adc
    pin: 6
    id: "VCC"
    internal: true
    
  - platform: template
    name: "Battery Level"
    unit_of_measurement: '%'
    update_interval: 5s
    lambda: |-
      return ((id(VCC).state /3.30) * 100.00);

  - platform: template
    name: "Battery Voltage"
    update_interval: 5s
    lambda: |-
      return id(ADC3).state;

binary_sensor:
  - platform: status
    name: "Status"
  - platform: gpio
    pin:
      number: 8
      mode: INPUT
    name: "Door"
    device_class: door
  

