  
esphome:
  name: $name
  friendly_name: $friendly_name

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  
logger:

web_server:

captive_portal:

mdns:

api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: ${name}
    password: !secret wifi_password

  manual_ip:
    static_ip: ${static_ip}
    gateway: !secret gateway
    subnet: !secret subnet

button:
  - platform: restart
    name: Restart

debug:
  update_interval: 500s

text_sensor:
  - platform: debug
    reset_reason:
      name: Reset Reason
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Wifi SSID
    mac_address:
      name: MAC
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true

sensor:
  - platform: uptime
    name: Uptime
    update_interval: 30s
  - platform: wifi_signal
    name: Wifi Signal
    update_interval: 500s

  - platform: adc
    pin: 3
    id: "VCC"
    internal: true
    filters:
      - multiply: 3.3
    
  - platform: template
    name: "Battery Level"
    unit_of_measurement: '%'
    update_interval: 500s
    lambda: |-
      return ((id(VCC).state /3.30) * 100.00);

  - platform: template
    name: "Battery Voltage"
    update_interval: 500s
    lambda: |-
      return id(VCC).state;

binary_sensor:
  - platform: status
    name: "Status"

  - platform: gpio
    pin:
      number: GPIO18
      mode: INPUT
    name: "Door"
    device_class: door
  