esphome:
  name: upk2esphome-bk7231n

bk72xx:
  board: generic-bk7231n-qfn32-tuya

logger:

web_server:

captive_portal:

mdns:

api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

button:
  - platform: restart
    name: Restart

debug:
  update_interval: 30s

text_sensor:
  - platform: debug
    reset_reason:
      name: Reset Reason
  - platform: libretiny
    version:
      name: LibreTiny Version
  - platform: template
    id: tuya_battery_state
    name: (Unconfirmed) Battery State
    filters:
      - map:
          - 0 -> Low
          - 1 -> Middle
          - 2 -> High

sensor:
  - platform: uptime
    name: Uptime

uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 9600

tuya:
  # DPIDs processed from schema model: 000003agra
  on_datapoint_update:
    - sensor_datapoint: 3
      datapoint_type: enum
      then:
        - text_sensor.template.publish:
            id: tuya_battery_state
            state: !lambda "return std::to_string(x);"

binary_sensor:
  - platform: tuya
    sensor_datapoint: 1
    name: (Unconfirmed) Doorcontact State
