substitutions:
  friendly_name: "Outside Front Left"
  name: "outside-front-left"
  store_scene_to_flash: "false"
  static_ip: 10.20.20.150
  gateway: 10.20.20.1
  subnet: 255.255.255.0

# by default controlling is done via the button and via the web interface
# if you use homeassistant you can uncomment below code:
#api:
#  password: !secret api_password

packages:
  remote_package:
    url: https://github.com/f03809/huckleberry.git
    ref: main
    refresh: 1s
    files: [base.yaml, atomi_sconce.yaml]