substitutions:
  default_transition_length: 2s

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

bk72xx:
  board: generic-bk7231n-qfn32-tuya

output:
  - platform: libretiny_pwm
    id: output_red
    pin: P26
    min_power: 0.01
    max_power : 0.90
  - platform: libretiny_pwm
    id: output_green
    pin: P24
    min_power: 0.01
    max_power : 0.90
  - platform: libretiny_pwm
    id: output_blue
    pin: P6
    min_power: 0.01
    max_power : 0.90
  - platform: libretiny_pwm
    id: output_cold
    pin: P8
    min_power: 0.01
    max_power : 0.90
  - platform: libretiny_pwm
    id: output_warm
    pin: P7
    min_power: 0.01
    max_power : 0.90

light:
  - platform: rgbww
    id: light_rgbww
    name: Light
    color_interlock: true
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_cold
    warm_white: output_warm
    default_transition_length: $default_transition_length
    restore_mode: RESTORE_DEFAULT_ON
