esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  platform: ESP8266
  board: esp8285

i2c:
  sda: GPIO13
  scl: GPIO04

number:
  - platform: template
    name: "On Humidity Threshold"
    id: on_humidity_threshold_ui
    unit_of_measurement: "%"
    min_value: 0
    max_value: 100
    step: 5
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: ${on_humidity_threshold}
    icon: "mdi:water-percent"
    entity_category: config
    on_value:
      - lambda: 'id(aht10_sensor).update();'
  - platform: template
    name: "Off Humidity Threshold"
    id: off_humidity_threshold_ui
    unit_of_measurement: "%"
    min_value: 0
    max_value: 100
    step: 5
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: ${off_humidity_threshold}
    icon: "mdi:water-percent"
    entity_category: config
    on_value:
      - lambda: 'id(aht10_sensor).update();'

sensor:
  - platform: aht10
    variant: AHT10
    id: aht10_sensor
    update_interval: 30s
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
      on_value:
        then:
          - lambda: |-
              if (x >= id(on_humidity_threshold_ui).state) {
                id(relay).turn_on();
              } else if (x >= id(off_humidity_threshold_ui).state) {
                id(relay).turn_off();
              }

switch:
  - platform: gpio
    id: relay
    name: "${friendly_name}"
    icon: mdi:fan
    pin: GPIO05
    on_turn_on:
      - switch.turn_on: blue_led
      - switch.turn_off: red_led
    on_turn_off:
      - switch.turn_on: blue_led
      - switch.turn_on: red_led
  - platform: gpio
    pin: GPIO12
    id: red_led
    internal: true
    inverted: true
  - platform: gpio
    pin: GPIO14
    id: blue_led
    internal: true
    inverted: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO03
      mode: INPUT_PULLUP
      inverted: true
    id: main_button
    internal: true
    on_press:
      - switch.toggle: relay